<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_jAaLoAnUEe65vrT_k-xexg" name="FechoDeProjeto" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_jAaLoQnUEe65vrT_k-xexg" name="Fecho de Projeto">
      <elements xmi:type="process:Lane" xmi:id="_jAaLognUEe65vrT_k-xexg" name="Consultores" actor="_jAaLuwnUEe65vrT_k-xexg">
        <elements xmi:type="process:Task" xmi:id="_FBmjoAnWEe65vrT_k-xexg" name="Dar atividades como completas" outgoing="_tR6wUAnXEe65vrT_k-xexg" incoming="_3oAFSwnVEe65vrT_k-xexg" overrideActorsOfTheLane="false">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_hR0csAnxEe6tX-7CHFY2xQ" source="_hRtvAAnxEe6tX-7CHFY2xQ"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3oAFQQnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3oAFQAnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3oAFQgnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_vcxS8goGEe6tX-7CHFY2xQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_vcxS8woGEe6tX-7CHFY2xQ" name="fechoProjeto" content="fechoProjeto" type="TYPE_VARIABLE" returnType="com.estg.model.FechoProjeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_vcxS9AoGEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_vcxS9QoGEe6tX-7CHFY2xQ" name="fechoProjetoInput.atividadesCompletas" content="fechoProjetoInput?.atividadesCompletas" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_vcxS9goGEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_vcxS9woGEe6tX-7CHFY2xQ" type="JAVA_METHOD" expression="setAtividadesCompletas">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3oAFQwnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3oAFRAnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_3oAFRQnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_3oAFRwnVEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_3oAFRgnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_FBnKuQnWEe65vrT_k-xexg">
            <targetForm xmi:type="expression:Expression" xmi:id="_xGMOMAoOEe67b-NuRHXGrA" name="atividadesCompletasForm" content="5b596d9c-ec1e-4c78-b8d3-27e1bace1d0c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_FBnKuAnWEe65vrT_k-xexg">
            <inputs xmi:type="process:ContractInput" xmi:id="_vcxS8AoGEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" dataReference="fechoProjeto" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_vcxS8QoGEe6tX-7CHFY2xQ" name="atividadesCompletas" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_FBnKuwnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_hRtvAAnxEe6tX-7CHFY2xQ" text="*** FALTA O RELÓGIO***"/>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_ntu2YAnUEe65vrT_k-xexg" name="Gestor de Projeto ou Gestor de Implementação" actor="_jAaLuwnUEe65vrT_k-xexg">
        <elements xmi:type="process:StartEvent" xmi:id="_jAaLownUEe65vrT_k-xexg" name="Projeto pronto a fechar" outgoing="_jAaLuAnUEe65vrT_k-xexg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jAaLpAnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jAaLpQnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jAaLpgnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_jAaLpwnUEe65vrT_k-xexg" name="Obter o tipo de projeto" outgoing="_1svH4AnUEe65vrT_k-xexg" incoming="_jAaLuAnUEe65vrT_k-xexg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jAaLqAnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jAaLqQnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jAaLqgnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_TeTCcAnxEe6tX-7CHFY2xQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_TeTCcQnxEe6tX-7CHFY2xQ" name="fechoProjeto" content="fechoProjeto" type="TYPE_VARIABLE" returnType="com.estg.model.FechoProjeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_TeTCcgnxEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_TeTCcwnxEe6tX-7CHFY2xQ" name="fechoProjetoInput.tipoProjetoABC" content="fechoProjetoInput?.tipoProjetoABC" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_TeTCdAnxEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_TeTCdQnxEe6tX-7CHFY2xQ" type="JAVA_METHOD" expression="setTipoProjetoABC">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jAaLqwnUEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jAaLrAnUEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jAaLrQnUEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jAaLrgnUEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jAaLrwnUEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_jAaLsAnUEe65vrT_k-xexg">
            <targetForm xmi:type="expression:Expression" xmi:id="_Uoe9oAnxEe6tX-7CHFY2xQ" name="obterTipoProjetoForm" content="e981b7ba-32c4-4616-9ac7-6b2ff85da874" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_jAaLsgnUEe65vrT_k-xexg">
            <inputs xmi:type="process:ContractInput" xmi:id="_TeSbYAnxEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" dataReference="fechoProjeto" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_TeSbYQnxEe6tX-7CHFY2xQ" name="tipoProjetoABC" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_jAaLswnUEe65vrT_k-xexg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_-Rmr8AnUEe65vrT_k-xexg" name="Decidir a necessidade de convocar uma reunião" outgoing="_ZQSVkAn5Ee6tX-7CHFY2xQ" incoming="_8h63AAnUEe65vrT_k-xexg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8h6P8gnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8h6P8QnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8h6P8wnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_qtoP0gnxEe6tX-7CHFY2xQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qtoP0wnxEe6tX-7CHFY2xQ" name="fechoProjeto" content="fechoProjeto" type="TYPE_VARIABLE" returnType="com.estg.model.FechoProjeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qtoP1AnxEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qtoP1QnxEe6tX-7CHFY2xQ" name="fechoProjetoInput.necessidadeReuniao" content="fechoProjetoInput?.necessidadeReuniao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qtoP1gnxEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qtoP1wnxEe6tX-7CHFY2xQ" type="JAVA_METHOD" expression="setNecessidadeReuniao">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8h6P9AnUEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8h6P9QnUEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8h6P9gnUEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8h6P-AnUEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8h6P9wnUEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_-RnTCQnUEe65vrT_k-xexg">
            <targetForm xmi:type="expression:Expression" xmi:id="_rhhK4AnxEe6tX-7CHFY2xQ" name="decidirNecessidadeReuniaoForm" content="30219656-97b7-469e-8572-64082dc5c58d" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_-RnTCAnUEe65vrT_k-xexg">
            <inputs xmi:type="process:ContractInput" xmi:id="_qtoP0AnxEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" dataReference="fechoProjeto" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_qtoP0QnxEe6tX-7CHFY2xQ" name="necessidadeReuniao" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_-RnTCwnUEe65vrT_k-xexg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Aou7YAnVEe65vrT_k-xexg" name="Tipo de projeto A, B ou C?" outgoing="_8CgXKAnUEe65vrT_k-xexg _8h63AAnUEe65vrT_k-xexg" incoming="_1svH4AnUEe65vrT_k-xexg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1stSsQnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1stSsAnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1stSsgnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_A7AXIAnVEe65vrT_k-xexg" name="Gateway1" outgoing="_T_hJ4AnVEe65vrT_k-xexg" incoming="_8CgXKAnUEe65vrT_k-xexg _ae9IIAn5Ee6tX-7CHFY2xQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8CgXIgnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8CgXIQnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8CgXIwnUEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_VByfMAnVEe65vrT_k-xexg" name="Marcar Reunião" outgoing="_YC3qkwnVEe65vrT_k-xexg" incoming="_T_hJ4AnVEe65vrT_k-xexg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_T_gi0QnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_T_gi0AnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_T_gi0gnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_T_gi0wnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_T_gi1AnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_T_gi1QnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_T_gi1wnVEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_T_gi1gnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_VByfNAnVEe65vrT_k-xexg" name="Marcar Reunião" content="Marcar Reunião" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_VByfNQnVEe65vrT_k-xexg" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_ZO4xwAnVEe65vrT_k-xexg" name="Realizar reunião de fecho do projeto" outgoing="_d7dOlwnVEe65vrT_k-xexg" incoming="_YC3qkwnVEe65vrT_k-xexg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YC3DggnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YC3DgQnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YC3DgwnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_YC3DhAnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_YC3DhQnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_YC3DhgnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_YC3DiAnVEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_YC3DhwnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_ZO4xxAnVEe65vrT_k-xexg" name="Reunião de Fecho do Projeto" content="Reunião de Fecho do Projeto" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_ZO4xxQnVEe65vrT_k-xexg" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_eF0EcAnVEe65vrT_k-xexg" name="Gateway2" outgoing="_NZoToAnYEe65vrT_k-xexg" incoming="_d7dOlwnVEe65vrT_k-xexg _ZxoIEAn5Ee6tX-7CHFY2xQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d7dOkQnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d7dOkAnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d7dOkgnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_jxi4MAnVEe65vrT_k-xexg" name="Tipo do projeto?" outgoing="_l5cY0AnVEe65vrT_k-xexg _sBt-qgnVEe65vrT_k-xexg" incoming="_OSIB4AnYEe65vrT_k-xexg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_i8CzkQnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_i8CzkAnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_i8CzkgnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_l5bxwAnVEe65vrT_k-xexg" name="Obter atividades agendadas no CRM" outgoing="_1NgYwAnVEe65vrT_k-xexg" incoming="_l5cY0AnVEe65vrT_k-xexg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_l5bxwgnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_l5bxwQnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_l5bxwwnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_l5bxxAnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_l5bxxQnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_l5bxxgnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_l5bxyAnVEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_l5bxxwnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ucafcAnVEe65vrT_k-xexg" name="Formalizar a documentação do encerramento" outgoing="_yeIp0AoUEe67ybv37Ys8Ww" incoming="_sBt-qgnVEe65vrT_k-xexg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sBt-oAnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sBtXkQnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sBt-oQnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_ikYLkgoDEe6tX-7CHFY2xQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_ikYLkwoDEe6tX-7CHFY2xQ" name="fechoProjeto" content="fechoProjeto" type="TYPE_VARIABLE" returnType="com.estg.model.FechoProjeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ikYLlAoDEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_ikYLlQoDEe6tX-7CHFY2xQ" name="fechoProjetoInput.documentacaoFormalizada" content="fechoProjetoInput?.documentacaoFormalizada" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ikYLlgoDEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_ikYLlwoDEe6tX-7CHFY2xQ" type="JAVA_METHOD" expression="setDocumentacaoFormalizada">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_sBt-ognVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_sBt-ownVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_sBt-pAnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_sBt-pgnVEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_sBt-pQnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ucafegnVEe65vrT_k-xexg">
            <targetForm xmi:type="expression:Expression" xmi:id="_er3A4AoOEe67b-NuRHXGrA" name="formalizarDocEncerramentoForm" content="b6c3f025-5560-4d70-bd0b-475eb6a43b6e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ucafeQnVEe65vrT_k-xexg">
            <inputs xmi:type="process:ContractInput" xmi:id="_ikYLkAoDEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" dataReference="fechoProjeto" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_ikYLkQoDEe6tX-7CHFY2xQ" name="documentacaoFormalizada" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ucaffAnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_2Bv5IAnVEe65vrT_k-xexg" name="Realizar atividades" outgoing="_3oAFSwnVEe65vrT_k-xexg" incoming="_1NgYwAnVEe65vrT_k-xexg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1NfxsgnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1NfxsQnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1NfxswnVEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_hmI6UgoGEe6tX-7CHFY2xQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_hmI6UwoGEe6tX-7CHFY2xQ" name="fechoProjeto" content="fechoProjeto" type="TYPE_VARIABLE" returnType="com.estg.model.FechoProjeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hmI6VAoGEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_hmI6VQoGEe6tX-7CHFY2xQ" name="fechoProjetoInput.atividadesRealizadas" content="fechoProjetoInput?.atividadesRealizadas" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_hmI6VgoGEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_hmI6VwoGEe6tX-7CHFY2xQ" type="JAVA_METHOD" expression="setAtividadesRealizadas">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1NfxtAnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1NfxtQnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1NfxtgnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1NfxuAnVEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1NfxtwnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_2Bv5KgnVEe65vrT_k-xexg">
            <targetForm xmi:type="expression:Expression" xmi:id="_u9DXcAoOEe67b-NuRHXGrA" name="realizarAtividadesForm" content="45b53cfa-da99-4151-a611-fe2d6af0ca8a" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_2Bv5KQnVEe65vrT_k-xexg">
            <inputs xmi:type="process:ContractInput" xmi:id="_hmI6UAoGEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" dataReference="fechoProjeto" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_hmI6UQoGEe6tX-7CHFY2xQ" name="atividadesRealizadas" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_2Bv5LAnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_UPN9UAnWEe65vrT_k-xexg" name="Enviar ao cliente" outgoing="_VSNEUAnWEe65vrT_k-xexg" incoming="_y6hD0AoUEe67ybv37Ys8Ww">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UPOkYQnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UPOkYAnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UPOkYgnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_UPOkYwnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_UPOkZAnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_UPOkZQnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_UPOkZwnWEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_UPOkZgnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_d1abgAnWEe65vrT_k-xexg" name="Cliente aceitou o fecho do projeto?" outgoing="_hL-utwnWEe65vrT_k-xexg _1nP5CAnWEe65vrT_k-xexg" incoming="_cK7PpAnWEe65vrT_k-xexg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_cK6okgnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_cK6okQnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_cK6okwnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_vbTUIAnWEe65vrT_k-xexg" name="Esperar a validação do cliente" outgoing="_cK7PpAnWEe65vrT_k-xexg" incoming="_VSNEUAnWEe65vrT_k-xexg" overrideActorsOfTheLane="false">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_j87_IQnxEe6tX-7CHFY2xQ" source="_j87YEAnxEe6tX-7CHFY2xQ"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VSMdQgnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VSMdQQnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VSMdQwnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_XmRX4goGEe6tX-7CHFY2xQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_XmRX4woGEe6tX-7CHFY2xQ" name="fechoProjeto" content="fechoProjeto" type="TYPE_VARIABLE" returnType="com.estg.model.FechoProjeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_XmRX5AoGEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_XmRX5QoGEe6tX-7CHFY2xQ" name="fechoProjetoInput.validacaoClienteObtida" content="fechoProjetoInput?.validacaoClienteObtida" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_XmRX5goGEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_XmRX5woGEe6tX-7CHFY2xQ" type="JAVA_METHOD" expression="setValidacaoClienteObtida">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VSMdRAnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VSMdRQnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VSMdRgnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VSMdSAnWEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VSMdRwnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="__esEIAoWEe67ybv37Ys8Ww" name="prazo estipulado no documento" outgoing="_83vakAoXEe67ybv37Ys8Ww">
            <condition xmi:type="expression:Expression" xmi:id="_DUZKYAoXEe67ybv37Ys8Ww" name="getPrazoDeValidacao()" content="fechoProjeto.prazoValidacao.toEpochSecond()*1000" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_YT31AAoXEe67ybv37Ys8Ww" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
            </condition>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_vbT7OQnWEe65vrT_k-xexg">
            <targetForm xmi:type="expression:Expression" xmi:id="_g8iDAAoOEe67b-NuRHXGrA" name="esperarValidacaoClienteForm" content="175050b9-6887-48ad-ad22-afc09127ae16" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_vbT7OAnWEe65vrT_k-xexg">
            <inputs xmi:type="process:ContractInput" xmi:id="_XmRX4AoGEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" dataReference="fechoProjeto" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_XmRX4QoGEe6tX-7CHFY2xQ" name="validacaoClienteObtida" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_vbT7OwnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_OtBOIAnYEe65vrT_k-xexg" name="Identificar tipo do projeto" outgoing="_OSIB4AnYEe65vrT_k-xexg" incoming="_NZoToAnYEe65vrT_k-xexg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NZnskgnYEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NZnskQnYEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NZnskwnYEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_YxACcgoCEe6tX-7CHFY2xQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_YxACcwoCEe6tX-7CHFY2xQ" name="fechoProjeto" content="fechoProjeto" type="TYPE_VARIABLE" returnType="com.estg.model.FechoProjeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_YxACdAoCEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_YxACdQoCEe6tX-7CHFY2xQ" name="fechoProjetoInput.tipoProjeto" content="fechoProjetoInput?.tipoProjeto" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_YxACdgoCEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_YxACdwoCEe6tX-7CHFY2xQ" type="JAVA_METHOD" expression="setTipoProjeto">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_NZnslAnYEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_NZnslQnYEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_NZnslgnYEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_NZnsmAnYEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_NZnslwnYEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_OtB1OQnYEe65vrT_k-xexg">
            <targetForm xmi:type="expression:Expression" xmi:id="_bizlQAoOEe67b-NuRHXGrA" name="identificarTipoProjetoForm" content="cecf3302-600e-4917-9361-37f568cf4987" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_OtB1OAnYEe65vrT_k-xexg">
            <inputs xmi:type="process:ContractInput" xmi:id="_YxACcAoCEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" dataReference="fechoProjeto" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_YxACcQoCEe6tX-7CHFY2xQ" name="tipoProjeto" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_OtB1OwnYEe65vrT_k-xexg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_j87YEAnxEe6tX-7CHFY2xQ" text="***FALTA O RELÓGIO***"/>
        <elements xmi:type="process:XORGateway" xmi:id="_ZhLRQAn5Ee6tX-7CHFY2xQ" name="Necessária reunião?" outgoing="_ZxoIEAn5Ee6tX-7CHFY2xQ _ae9IIAn5Ee6tX-7CHFY2xQ" incoming="_ZQSVkAn5Ee6tX-7CHFY2xQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZQRugQn5Ee6tX-7CHFY2xQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZQRugAn5Ee6tX-7CHFY2xQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZQRuggn5Ee6tX-7CHFY2xQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_5E4UUAoUEe67ybv37Ys8Ww" name="Obter o prazo de validação estipulado no documento" outgoing="_y6hD0AoUEe67ybv37Ys8Ww" incoming="_yeIp0AoUEe67ybv37Ys8Ww" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yeHbsQoUEe67ybv37Ys8Ww" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yeHbsAoUEe67ybv37Ys8Ww" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yeHbsgoUEe67ybv37Ys8Ww" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_6ZndMAoVEe67ybv37Ys8Ww">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6ZndMQoVEe67ybv37Ys8Ww" name="fechoProjeto" content="fechoProjeto" type="TYPE_VARIABLE" returnType="com.estg.model.FechoProjeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6ZndMgoVEe67ybv37Ys8Ww" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6ZndMwoVEe67ybv37Ys8Ww" name="fechoProjetoInput.prazoValidacao" content="fechoProjetoInput?.prazoValidacao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.OffsetDateTime">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6ZndNAoVEe67ybv37Ys8Ww" name="fechoProjetoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6ZndNQoVEe67ybv37Ys8Ww" type="JAVA_METHOD" expression="setPrazoValidacao">
              <inputTypes>java.time.OffsetDateTime</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yeHbswoUEe67ybv37Ys8Ww" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yeHbtAoUEe67ybv37Ys8Ww" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yeHbtQoUEe67ybv37Ys8Ww" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yeHbtwoUEe67ybv37Ys8Ww" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yeHbtgoUEe67ybv37Ys8Ww" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_5E47ZQoUEe67ybv37Ys8Ww">
            <targetForm xmi:type="expression:Expression" xmi:id="_bZzrMAoXEe67ybv37Ys8Ww" name="PrazoValidacaoFechoProjetoForm" content="2a800a1b-5305-4291-89cd-bdfe210e911c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_5E47ZAoUEe67ybv37Ys8Ww">
            <inputs xmi:type="process:ContractInput" xmi:id="_6Zm2IAoVEe67ybv37Ys8Ww" name="fechoProjetoInput" type="COMPLEX" dataReference="fechoProjeto" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_6Zm2IQoVEe67ybv37Ys8Ww" name="prazoValidacao" type="OFFSETDATETIME" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_7QjsQAoVEe67ybv37Ys8Ww" expression="return fechoProjetoInput.prazoValidacao.toEpochSecond()*1000-(new Date()).getTime()>60*60*1;" errorMessage="O prazo de validação tem de ser no mínimo uma hora depois" name="minPrazo">
              <inputNames>fechoProjetoInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_5E47ZwoUEe67ybv37Ys8Ww" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_n3LGQAnUEe65vrT_k-xexg" name="Gestor de Conta ou Gestor da equipa" actor="_jAaLuwnUEe65vrT_k-xexg">
        <elements xmi:type="process:Task" xmi:id="_-vOKIAnWEe65vrT_k-xexg" name="Decidir se o projeto deve ser ou não encerrado" outgoing="_A91WwAnXEe65vrT_k-xexg" incoming="_9aNfAwnWEe65vrT_k-xexg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9aM38gnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9aM38QnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9aM38wnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_fzLScgoHEe6tX-7CHFY2xQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_fzLScwoHEe6tX-7CHFY2xQ" name="fechoProjeto" content="fechoProjeto" type="TYPE_VARIABLE" returnType="com.estg.model.FechoProjeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_fzLSdAoHEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_fzLSdQoHEe6tX-7CHFY2xQ" name="fechoProjetoInput.projetoDeveSerEncerrado" content="fechoProjetoInput?.projetoDeveSerEncerrado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_fzLSdgoHEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_fzLSdwoHEe6tX-7CHFY2xQ" type="JAVA_METHOD" expression="setProjetoDeveSerEncerrado">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_9aM39AnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_9aM39QnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_9aM39gnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_9aM3-AnWEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_9aM39wnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_-vOKKgnWEe65vrT_k-xexg">
            <targetForm xmi:type="expression:Expression" xmi:id="_rzOfwAoOEe67b-NuRHXGrA" name="projetoDeveSerEncerradoForm" content="5a27d4cd-901b-4f30-b3d4-afd55c2d2114" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_-vOKKQnWEe65vrT_k-xexg">
            <inputs xmi:type="process:ContractInput" xmi:id="_fzLScAoHEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" dataReference="fechoProjeto" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_fzLScQoHEe6tX-7CHFY2xQ" name="projetoDeveSerEncerrado" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_-vOKLAnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_DbzOAAnXEe65vrT_k-xexg" name="Encerrar projeto?" outgoing="_FekXBwnXEe65vrT_k-xexg _IXV6-AnXEe65vrT_k-xexg" incoming="_A91WwAnXEe65vrT_k-xexg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_A90vsgnXEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_A90vsQnXEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_A90vswnXEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Fejv8AnXEe65vrT_k-xexg" name="Projeto terminado" incoming="_FekXBwnXEe65vrT_k-xexg _mzWKYAnXEe65vrT_k-xexg _tR6wUAnXEe65vrT_k-xexg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_FekXAQnXEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_FekXAAnXEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_FekXAgnXEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_IXV68AnXEe65vrT_k-xexg" name="Projeto não terminado" incoming="_IXV6-AnXEe65vrT_k-xexg _gFpjUAnXEe65vrT_k-xexg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IXV68gnXEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IXV68QnXEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IXV68wnXEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_oA6REAnUEe65vrT_k-xexg" name="Gestor de Projeto" actor="_jAaLuwnUEe65vrT_k-xexg">
        <elements xmi:type="process:XORGateway" xmi:id="_hg2ygAnWEe65vrT_k-xexg" name="Gateway3" outgoing="_iobemwnWEe65vrT_k-xexg" incoming="_hL-utwnWEe65vrT_k-xexg _83vakAoXEe67ybv37Ys8Ww">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hL-usQnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hL-usAnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hL-usgnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_ioa3gAnWEe65vrT_k-xexg" name="Dar o processo como encerrado no CRM" outgoing="_mzWKYAnXEe65vrT_k-xexg" incoming="_iobemwnWEe65vrT_k-xexg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iobekQnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iobekAnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iobekgnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_iobekwnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_iobelAnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_iobelQnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_iobelwnWEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_iobelgnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_3eOowAnWEe65vrT_k-xexg" name="Identificar aspetos considerados em aberto" outgoing="_7owvggnWEe65vrT_k-xexg" incoming="_1nP5CAnWEe65vrT_k-xexg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1nPR8gnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1nPR8QnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1nPR8wnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_HuIlEgoHEe6tX-7CHFY2xQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_HuIlEwoHEe6tX-7CHFY2xQ" name="fechoProjeto" content="fechoProjeto" type="TYPE_VARIABLE" returnType="com.estg.model.FechoProjeto">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_HuIlFAoHEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_HuIlFQoHEe6tX-7CHFY2xQ" name="fechoProjetoInput.aspetosAbertos" content="fechoProjetoInput?.aspetosAbertos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_HuIlFgoHEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_HuIlFwoHEe6tX-7CHFY2xQ" type="JAVA_METHOD" expression="setAspetosAbertos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1nP5AAnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1nP5AQnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1nP5AgnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1nP5BAnWEe65vrT_k-xexg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1nP5AwnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_3eOoygnWEe65vrT_k-xexg">
            <targetForm xmi:type="expression:Expression" xmi:id="_pHaZwAoOEe67b-NuRHXGrA" name="aspetosConsideradosAbertoForm" content="5c972ebc-3f07-45db-93a2-3ff67ca0cf0b" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_3eOoyQnWEe65vrT_k-xexg">
            <inputs xmi:type="process:ContractInput" xmi:id="_HuIlEAoHEe6tX-7CHFY2xQ" name="fechoProjetoInput" type="COMPLEX" dataReference="fechoProjeto" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_HuIlEQoHEe6tX-7CHFY2xQ" name="aspetosAbertos" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_3eOozAnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_DEtjsAnXEe65vrT_k-xexg" name="Concorda com o cliente?" outgoing="_9aNfAwnWEe65vrT_k-xexg _gFpjUAnXEe65vrT_k-xexg" incoming="_7owvggnWEe65vrT_k-xexg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7owIcgnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7owIcQnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7owIcwnWEe65vrT_k-xexg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_mNleAAnvEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto">
        <defaultValue xmi:type="expression:Expression" xmi:id="_mNleAQnvEe6tX-7CHFY2xQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_jAaLtAnUEe65vrT_k-xexg">
        <targetForm xmi:type="expression:Expression" xmi:id="_0nOsAAoOEe67b-NuRHXGrA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_jAaLtgnUEe65vrT_k-xexg">
        <targetForm xmi:type="expression:Expression" xmi:id="_jAaLtwnUEe65vrT_k-xexg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jAaLuAnUEe65vrT_k-xexg" target="_jAaLpwnUEe65vrT_k-xexg" source="_jAaLownUEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jAaLuQnUEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_jAaLugnUEe65vrT_k-xexg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1svH4AnUEe65vrT_k-xexg" target="_Aou7YAnVEe65vrT_k-xexg" source="_jAaLpwnUEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1svu8AnUEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_1svu8QnUEe65vrT_k-xexg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8CgXKAnUEe65vrT_k-xexg" name="A" target="_A7AXIAnVEe65vrT_k-xexg" source="_Aou7YAnVEe65vrT_k-xexg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8Cg-MAnUEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_8Cg-MQnUEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8h63AAnUEe65vrT_k-xexg" name="B ou C" target="_-Rmr8AnUEe65vrT_k-xexg" source="_Aou7YAnVEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8h63AQnUEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_8h63AgnUEe65vrT_k-xexg" name="newScript()" content="fechoProjeto.tipoProjetoABC == &quot;B&quot; || fechoProjeto.tipoProjetoABC == &quot;C&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4PQ6wAnvEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_T_hJ4AnVEe65vrT_k-xexg" target="_VByfMAnVEe65vrT_k-xexg" source="_A7AXIAnVEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_T_hJ4QnVEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_T_hJ4gnVEe65vrT_k-xexg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YC3qkwnVEe65vrT_k-xexg" target="_ZO4xwAnVEe65vrT_k-xexg" source="_VByfMAnVEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YC3qlAnVEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_YC3qlQnVEe65vrT_k-xexg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_d7dOlwnVEe65vrT_k-xexg" target="_eF0EcAnVEe65vrT_k-xexg" source="_ZO4xwAnVEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_d7d1oAnVEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_d7d1oQnVEe65vrT_k-xexg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_l5cY0AnVEe65vrT_k-xexg" name="Consultoria ou Upgrade" target="_l5bxwAnVEe65vrT_k-xexg" source="_jxi4MAnVEe65vrT_k-xexg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_l5cY0QnVEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_l5cY0gnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sBt-qgnVEe65vrT_k-xexg" name="Conceção, desenvolvimento, implementação ou prototipagem" target="_ucafcAnVEe65vrT_k-xexg" source="_jxi4MAnVEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sBt-qwnVEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_sBt-rAnVEe65vrT_k-xexg" name="tipoProjeto()" content="fechoProjeto.tipoProjeto == &quot;Conceção&quot; || fechoProjeto.tipoProjeto == &quot;Desenvolvimento&quot; || fechoProjeto.tipoProjeto == &quot;Implementação&quot; || fechoProjeto.tipoProjeto == &quot;Prototipagem&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_D8qCEAoIEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1NgYwAnVEe65vrT_k-xexg" target="_2Bv5IAnVEe65vrT_k-xexg" source="_l5bxwAnVEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1NgYwQnVEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_1NgYwgnVEe65vrT_k-xexg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3oAFSwnVEe65vrT_k-xexg" target="_FBmjoAnWEe65vrT_k-xexg" source="_2Bv5IAnVEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3oAFTAnVEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_3oAFTQnVEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VSNEUAnWEe65vrT_k-xexg" target="_vbTUIAnWEe65vrT_k-xexg" source="_UPN9UAnWEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VSNEUQnWEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_VSNEUgnWEe65vrT_k-xexg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cK7PpAnWEe65vrT_k-xexg" target="_d1abgAnWEe65vrT_k-xexg" source="_vbTUIAnWEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cK7PpQnWEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_cK7PpgnWEe65vrT_k-xexg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hL-utwnWEe65vrT_k-xexg" name="sim" target="_hg2ygAnWEe65vrT_k-xexg" source="_d1abgAnWEe65vrT_k-xexg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hL-uuAnWEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_hL-uuQnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iobemwnWEe65vrT_k-xexg" target="_ioa3gAnWEe65vrT_k-xexg" source="_hg2ygAnWEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iobenAnWEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_iobenQnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1nP5CAnWEe65vrT_k-xexg" name="não" target="_3eOowAnWEe65vrT_k-xexg" source="_d1abgAnWEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1nP5CQnWEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_1nP5CgnWEe65vrT_k-xexg" name="naoObtidaValidacaoCliente()" content="!fechoProjeto.validacaoClienteObtida" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_U_dbwAoIEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7owvggnWEe65vrT_k-xexg" target="_DEtjsAnXEe65vrT_k-xexg" source="_3eOowAnWEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7owvgwnWEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_7owvhAnWEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9aNfAwnWEe65vrT_k-xexg" name="não" target="_-vOKIAnWEe65vrT_k-xexg" source="_DEtjsAnXEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9aNfBAnWEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_9aNfBQnWEe65vrT_k-xexg" name="naoConcordaComCliente()" content="!fechoProjeto.concordaComCliente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_W7KI4AoHEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_A91WwAnXEe65vrT_k-xexg" target="_DbzOAAnXEe65vrT_k-xexg" source="_-vOKIAnWEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_A91WwQnXEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_A91WwgnXEe65vrT_k-xexg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FekXBwnXEe65vrT_k-xexg" name="sim" target="_Fejv8AnXEe65vrT_k-xexg" source="_DbzOAAnXEe65vrT_k-xexg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FekXCAnXEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_FekXCQnXEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IXV6-AnXEe65vrT_k-xexg" name="não" target="_IXV68AnXEe65vrT_k-xexg" source="_DbzOAAnXEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IXV6-QnXEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IXV6-gnXEe65vrT_k-xexg" name="projetoNaoDeveSerEncerrado()" content="!fechoProjeto.projetoDeveSerEncerrado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_lqOlYAoHEe6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gFpjUAnXEe65vrT_k-xexg" name="sim" target="_IXV68AnXEe65vrT_k-xexg" source="_DEtjsAnXEe65vrT_k-xexg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gFpjUQnXEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_gFpjUgnXEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mzWKYAnXEe65vrT_k-xexg" target="_Fejv8AnXEe65vrT_k-xexg" source="_ioa3gAnWEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mzWKYQnXEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_mzWKYgnXEe65vrT_k-xexg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tR6wUAnXEe65vrT_k-xexg" target="_Fejv8AnXEe65vrT_k-xexg" source="_FBmjoAnWEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tR6wUQnXEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_tR6wUgnXEe65vrT_k-xexg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NZoToAnYEe65vrT_k-xexg" target="_OtBOIAnYEe65vrT_k-xexg" source="_eF0EcAnVEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NZoToQnYEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_NZoTognYEe65vrT_k-xexg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OSIB4AnYEe65vrT_k-xexg" target="_jxi4MAnVEe65vrT_k-xexg" source="_OtBOIAnYEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OSIB4QnYEe65vrT_k-xexg"/>
        <condition xmi:type="expression:Expression" xmi:id="_OSIB4gnYEe65vrT_k-xexg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZQSVkAn5Ee6tX-7CHFY2xQ" target="_ZhLRQAn5Ee6tX-7CHFY2xQ" source="_-Rmr8AnUEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZQSVkQn5Ee6tX-7CHFY2xQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZQSVkgn5Ee6tX-7CHFY2xQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZxoIEAn5Ee6tX-7CHFY2xQ" name="não" target="_eF0EcAnVEe65vrT_k-xexg" source="_ZhLRQAn5Ee6tX-7CHFY2xQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZxoIEQn5Ee6tX-7CHFY2xQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZxoIEgn5Ee6tX-7CHFY2xQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ae9IIAn5Ee6tX-7CHFY2xQ" name="sim" target="_A7AXIAnVEe65vrT_k-xexg" source="_ZhLRQAn5Ee6tX-7CHFY2xQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ae9IIQn5Ee6tX-7CHFY2xQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ae9IIgn5Ee6tX-7CHFY2xQ" name="necessidadeReuniao()" content="fechoProjeto.necessidadeReuniao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Vg0An5Ee6tX-7CHFY2xQ" name="fechoProjeto" dataType="_jAaL1AnUEe65vrT_k-xexg" className="com.estg.model.FechoProjeto"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yeIp0AoUEe67ybv37Ys8Ww" target="_5E4UUAoUEe67ybv37Ys8Ww" source="_ucafcAnVEe65vrT_k-xexg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yeIp0QoUEe67ybv37Ys8Ww"/>
        <condition xmi:type="expression:Expression" xmi:id="_yeIp0goUEe67ybv37Ys8Ww" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_y6hD0AoUEe67ybv37Ys8Ww" target="_UPN9UAnWEe65vrT_k-xexg" source="_5E4UUAoUEe67ybv37Ys8Ww">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_y6hD0QoUEe67ybv37Ys8Ww"/>
        <condition xmi:type="expression:Expression" xmi:id="_y6hD0goUEe67ybv37Ys8Ww" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_83vakAoXEe67ybv37Ys8Ww" target="_hg2ygAnWEe65vrT_k-xexg" source="__esEIAoWEe67ybv37Ys8Ww">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_83wBoAoXEe67ybv37Ys8Ww"/>
        <condition xmi:type="expression:Expression" xmi:id="_83wBoQoXEe67ybv37Ys8Ww" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_jAaLuwnUEe65vrT_k-xexg" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_jAaLvAnUEe65vrT_k-xexg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jAaLvQnUEe65vrT_k-xexg">
        <name xmi:type="expression:Expression" xmi:id="_jAaLvgnUEe65vrT_k-xexg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jAaLvwnUEe65vrT_k-xexg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jAaLwAnUEe65vrT_k-xexg">
        <name xmi:type="expression:Expression" xmi:id="_jAaLwQnUEe65vrT_k-xexg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jAaLwgnUEe65vrT_k-xexg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jAaLwwnUEe65vrT_k-xexg">
        <name xmi:type="expression:Expression" xmi:id="_jAaLxAnUEe65vrT_k-xexg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jAaLxQnUEe65vrT_k-xexg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jAaLxgnUEe65vrT_k-xexg">
        <name xmi:type="expression:Expression" xmi:id="_jAaLxwnUEe65vrT_k-xexg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jAaLyAnUEe65vrT_k-xexg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jAaLyQnUEe65vrT_k-xexg">
        <name xmi:type="expression:Expression" xmi:id="_jAaLygnUEe65vrT_k-xexg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jAaLywnUEe65vrT_k-xexg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_jAaLzAnUEe65vrT_k-xexg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_jAaLzQnUEe65vrT_k-xexg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_jAaLzgnUEe65vrT_k-xexg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_jAaLzwnUEe65vrT_k-xexg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_jAaL0AnUEe65vrT_k-xexg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_jAaL0QnUEe65vrT_k-xexg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_jAaL0gnUEe65vrT_k-xexg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_jAaL0wnUEe65vrT_k-xexg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_jAaL1AnUEe65vrT_k-xexg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_jAaL1QnUEe65vrT_k-xexg" type="Process" element="_jAaLoAnUEe65vrT_k-xexg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_jAaL1gnUEe65vrT_k-xexg" type="2007" element="_jAaLoQnUEe65vrT_k-xexg">
      <children xmi:type="notation:DecorationNode" xmi:id="_jAaL1wnUEe65vrT_k-xexg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_jAaL2AnUEe65vrT_k-xexg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_jAaL2QnUEe65vrT_k-xexg" type="3007" element="_jAaLognUEe65vrT_k-xexg">
          <children xmi:type="notation:DecorationNode" xmi:id="_jAaL2gnUEe65vrT_k-xexg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_jAaL2wnUEe65vrT_k-xexg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_FBnKvAnWEe65vrT_k-xexg" type="3005" element="_FBmjoAnWEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_FBnKvgnWEe65vrT_k-xexg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FBnKvQnWEe65vrT_k-xexg" x="1845" y="27" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_hRyngAnxEe6tX-7CHFY2xQ" type="3015" element="_hRtvAAnxEe6tX-7CHFY2xQ">
              <children xmi:type="notation:DecorationNode" xmi:id="_hRynhQnxEe6tX-7CHFY2xQ" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_hRyngQnxEe6tX-7CHFY2xQ"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_hRynggnxEe6tX-7CHFY2xQ" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_hRyngwnxEe6tX-7CHFY2xQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hRynhAnxEe6tX-7CHFY2xQ" x="2006" y="98"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_jAaL4wnUEe65vrT_k-xexg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_jAaL5AnUEe65vrT_k-xexg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_jAaL5QnUEe65vrT_k-xexg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_jAaL5gnUEe65vrT_k-xexg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jAaL5wnUEe65vrT_k-xexg" x="23" y="10" width="2647" height="180"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_ntwEgAnUEe65vrT_k-xexg" type="3007" element="_ntu2YAnUEe65vrT_k-xexg">
          <children xmi:type="notation:DecorationNode" xmi:id="_ntwrkwnUEe65vrT_k-xexg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_ntwrlAnUEe65vrT_k-xexg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_jAaL3wnUEe65vrT_k-xexg" type="3002" element="_jAaLownUEe65vrT_k-xexg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jAaL4AnUEe65vrT_k-xexg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jAaL4QnUEe65vrT_k-xexg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jAaL4gnUEe65vrT_k-xexg" x="89" y="185"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jAaL3AnUEe65vrT_k-xexg" type="3005" element="_jAaLpwnUEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jAaL3QnUEe65vrT_k-xexg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jAaL3gnUEe65vrT_k-xexg" x="213" y="170" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-RnTDAnUEe65vrT_k-xexg" type="3005" element="_-Rmr8AnUEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-RnTDgnUEe65vrT_k-xexg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-RnTDQnUEe65vrT_k-xexg" x="536" y="271" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_AovicAnVEe65vrT_k-xexg" type="3008" element="_Aou7YAnVEe65vrT_k-xexg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_AovicgnVEe65vrT_k-xexg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_AovicwnVEe65vrT_k-xexg" x="1" y="-76"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AovicQnVEe65vrT_k-xexg" x="442" y="178" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_A7AXJAnVEe65vrT_k-xexg" type="3008" element="_A7AXIAnVEe65vrT_k-xexg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_A7AXJgnVEe65vrT_k-xexg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_A7AXJwnVEe65vrT_k-xexg" x="1" y="-80"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_A7AXJQnVEe65vrT_k-xexg" x="727" y="182" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VByfOwnVEe65vrT_k-xexg" type="3063" element="_VByfMAnVEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_VByfPQnVEe65vrT_k-xexg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VByfPAnVEe65vrT_k-xexg" x="862" y="171" width="132" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZO4xywnVEe65vrT_k-xexg" type="3063" element="_ZO4xwAnVEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZO4xzQnVEe65vrT_k-xexg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZO4xzAnVEe65vrT_k-xexg" x="1068" y="163" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eF0rgwnVEe65vrT_k-xexg" type="3008" element="_eF0EcAnVEe65vrT_k-xexg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_eF0rhQnVEe65vrT_k-xexg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_eF0rhgnVEe65vrT_k-xexg" x="1" y="-77"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eF0rhAnVEe65vrT_k-xexg" x="1290" y="179" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jxi4NAnVEe65vrT_k-xexg" type="3008" element="_jxi4MAnVEe65vrT_k-xexg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jxi4NgnVEe65vrT_k-xexg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jxi4NwnVEe65vrT_k-xexg" x="5" y="-76"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jxi4NQnVEe65vrT_k-xexg" x="1524" y="178" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_l5bxyQnVEe65vrT_k-xexg" type="3027" element="_l5bxwAnVEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_l5bxywnVEe65vrT_k-xexg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_l5bxygnVEe65vrT_k-xexg" x="1676" y="62" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ucaffQnVEe65vrT_k-xexg" type="3005" element="_ucafcAnVEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ucaffwnVEe65vrT_k-xexg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ucaffgnVEe65vrT_k-xexg" x="1454" y="281" width="143" height="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2Bv5LQnVEe65vrT_k-xexg" type="3005" element="_2Bv5IAnVEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_2Bv5LwnVEe65vrT_k-xexg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2Bv5LgnVEe65vrT_k-xexg" x="1855" y="74" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UPOkaAnWEe65vrT_k-xexg" type="3027" element="_UPN9UAnWEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_UPOkagnWEe65vrT_k-xexg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UPOkaQnWEe65vrT_k-xexg" x="1882" y="285" width="125" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_d1abhAnWEe65vrT_k-xexg" type="3008" element="_d1abgAnWEe65vrT_k-xexg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_d1abhgnWEe65vrT_k-xexg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_d1abhwnWEe65vrT_k-xexg" x="41" y="-53"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_d1abhQnWEe65vrT_k-xexg" x="2253" y="298" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vbT7PAnWEe65vrT_k-xexg" type="3005" element="_vbTUIAnWEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vbT7PgnWEe65vrT_k-xexg" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="__esrMAoWEe67ybv37Ys8Ww" type="3043" element="__esEIAoWEe67ybv37Ys8Ww" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="__esrMgoWEe67ybv37Ys8Ww" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="__esrMwoWEe67ybv37Ys8Ww" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="__esrMQoWEe67ybv37Ys8Ww"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vbT7PQnWEe65vrT_k-xexg" x="2054" y="290" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OtB1PAnYEe65vrT_k-xexg" type="3005" element="_OtBOIAnYEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OtB1PgnYEe65vrT_k-xexg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OtB1PQnYEe65vrT_k-xexg" x="1360" y="167" width="132" height="66"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_j87YEQnxEe6tX-7CHFY2xQ" type="3015" element="_j87YEAnxEe6tX-7CHFY2xQ">
              <children xmi:type="notation:DecorationNode" xmi:id="_j87_IAnxEe6tX-7CHFY2xQ" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_j87YEgnxEe6tX-7CHFY2xQ"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_j87YEwnxEe6tX-7CHFY2xQ" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_j87YFAnxEe6tX-7CHFY2xQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_j87YFQnxEe6tX-7CHFY2xQ" x="2102" y="162"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZhLRRAn5Ee6tX-7CHFY2xQ" type="3008" element="_ZhLRQAn5Ee6tX-7CHFY2xQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZhLRRgn5Ee6tX-7CHFY2xQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZhLRRwn5Ee6tX-7CHFY2xQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZhLRRQn5Ee6tX-7CHFY2xQ" x="727" y="284" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5E47aAoUEe67ybv37Ys8Ww" type="3005" element="_5E4UUAoUEe67ybv37Ys8Ww" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5E47agoUEe67ybv37Ys8Ww" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5E47aQoUEe67ybv37Ys8Ww" x="1655" y="269" width="188" height="93"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_ntwEgQnUEe65vrT_k-xexg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_ntwrkAnUEe65vrT_k-xexg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_ntwrkQnUEe65vrT_k-xexg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_ntwrlQnUEe65vrT_k-xexg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ntwrkgnUEe65vrT_k-xexg" x="53" y="180" width="3392" height="417"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_n3LtUAnUEe65vrT_k-xexg" type="3007" element="_n3LGQAnUEe65vrT_k-xexg">
          <children xmi:type="notation:DecorationNode" xmi:id="_n3LtVQnUEe65vrT_k-xexg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_n3LtVgnUEe65vrT_k-xexg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_-vOKLQnWEe65vrT_k-xexg" type="3005" element="_-vOKIAnWEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-vOKLwnWEe65vrT_k-xexg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-vOKLgnWEe65vrT_k-xexg" x="2678" y="36" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DbzOBAnXEe65vrT_k-xexg" type="3008" element="_DbzOAAnXEe65vrT_k-xexg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_DbzOBgnXEe65vrT_k-xexg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_DbzOBwnXEe65vrT_k-xexg" x="1" y="-64"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DbzOBQnXEe65vrT_k-xexg" x="2896" y="50" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_FekXAwnXEe65vrT_k-xexg" type="3003" element="_Fejv8AnXEe65vrT_k-xexg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_FekXBQnXEe65vrT_k-xexg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_FekXBgnXEe65vrT_k-xexg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FekXBAnXEe65vrT_k-xexg" x="3253" y="55"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IXV69AnXEe65vrT_k-xexg" type="3003" element="_IXV68AnXEe65vrT_k-xexg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_IXV69gnXEe65vrT_k-xexg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IXV69wnXEe65vrT_k-xexg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IXV69QnXEe65vrT_k-xexg" x="3101" y="136"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_n3LtUQnUEe65vrT_k-xexg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_n3LtUgnUEe65vrT_k-xexg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_n3LtUwnUEe65vrT_k-xexg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_n3LtVwnUEe65vrT_k-xexg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_n3LtVAnUEe65vrT_k-xexg" x="48" y="500" width="1297" height="250"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_oA6REQnUEe65vrT_k-xexg" type="3007" element="_oA6REAnUEe65vrT_k-xexg">
          <children xmi:type="notation:DecorationNode" xmi:id="_oA64IAnUEe65vrT_k-xexg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_oA64IQnUEe65vrT_k-xexg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_hg2yhAnWEe65vrT_k-xexg" type="3008" element="_hg2ygAnWEe65vrT_k-xexg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_hg3ZkAnWEe65vrT_k-xexg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_hg3ZkQnWEe65vrT_k-xexg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hg2yhQnWEe65vrT_k-xexg" x="2212" y="55" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_iobemAnWEe65vrT_k-xexg" type="3027" element="_ioa3gAnWEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_iobemgnWEe65vrT_k-xexg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iobemQnWEe65vrT_k-xexg" x="2153" y="166" width="162" height="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3eOozQnWEe65vrT_k-xexg" type="3005" element="_3eOowAnWEe65vrT_k-xexg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_3eOozwnWEe65vrT_k-xexg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3eOozgnWEe65vrT_k-xexg" x="2322" y="38" width="156" height="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DEuKwwnXEe65vrT_k-xexg" type="3008" element="_DEtjsAnXEe65vrT_k-xexg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_DEuKxQnXEe65vrT_k-xexg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_DEuKxgnXEe65vrT_k-xexg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DEuKxAnXEe65vrT_k-xexg" x="2587" y="57" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_oA6REgnUEe65vrT_k-xexg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_oA6REwnUEe65vrT_k-xexg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_oA6RFAnUEe65vrT_k-xexg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_oA64IgnUEe65vrT_k-xexg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oA6RFQnUEe65vrT_k-xexg" x="23" y="830" width="2647" height="292"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_jAaL6AnUEe65vrT_k-xexg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_jAaL6QnUEe65vrT_k-xexg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_jAaL6gnUEe65vrT_k-xexg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_jAaL6wnUEe65vrT_k-xexg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jAaL7AnUEe65vrT_k-xexg" width="3420" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_jAaL7QnUEe65vrT_k-xexg"/>
    <edges xmi:type="notation:Connector" xmi:id="_jAaL7gnUEe65vrT_k-xexg" type="4001" element="_jAaLuAnUEe65vrT_k-xexg" source="_jAaL3wnUEe65vrT_k-xexg" target="_jAaL3AnUEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jAaL7wnUEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jAaL8AnUEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jAaL8QnUEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jAaL8gnUEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1syLMAnUEe65vrT_k-xexg" type="4001" element="_1svH4AnUEe65vrT_k-xexg" source="_jAaL3AnUEe65vrT_k-xexg" target="_AovicAnVEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1syLMwnUEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1syLNAnUEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1syLMQnUEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1syLMgnUEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8Cg-MgnUEe65vrT_k-xexg" type="4001" element="_8CgXKAnUEe65vrT_k-xexg" source="_AovicAnVEe65vrT_k-xexg" target="_A7AXJAnVEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8Cg-NQnUEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8Cg-NgnUEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8Cg-MwnUEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8Cg-NAnUEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8h63AwnUEe65vrT_k-xexg" type="4001" element="_8h63AAnUEe65vrT_k-xexg" source="_AovicAnVEe65vrT_k-xexg" target="_-RnTDAnUEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8h63BgnUEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8h63BwnUEe65vrT_k-xexg" x="30" y="-23"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8h63BAnUEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8h63BQnUEe65vrT_k-xexg" points="[0, 22, -143, -85]$[0, 106, -143, -1]$[73, 106, -70, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_T_hJ4wnVEe65vrT_k-xexg" type="4001" element="_T_hJ4AnVEe65vrT_k-xexg" source="_A7AXJAnVEe65vrT_k-xexg" target="_VByfOwnVEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_T_hJ5gnVEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_T_hJ5wnVEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_T_hJ5AnVEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_T_hJ5QnVEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YC3qlgnVEe65vrT_k-xexg" type="4001" element="_YC3qkwnVEe65vrT_k-xexg" source="_VByfOwnVEe65vrT_k-xexg" target="_ZO4xywnVEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YC3qmQnVEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YC3qmgnVEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YC3qlwnVEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YC3qmAnVEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_d7d1ognVEe65vrT_k-xexg" type="4001" element="_d7dOlwnVEe65vrT_k-xexg" source="_ZO4xywnVEe65vrT_k-xexg" target="_eF0rgwnVEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d7d1pQnVEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d7d1pgnVEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d7d1ownVEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_d7d1pAnVEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_l5cY0wnVEe65vrT_k-xexg" type="4001" element="_l5cY0AnVEe65vrT_k-xexg" source="_jxi4NAnVEe65vrT_k-xexg" target="_l5bxyQnVEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_l5cY1gnVEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_l5cY1wnVEe65vrT_k-xexg" x="-35" y="-13"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_l5cY1AnVEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_l5cY1QnVEe65vrT_k-xexg" points="[22, 0, -163, 101]$[194, 0, 9, 101]$[194, -64, 9, 37]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sBt-rQnVEe65vrT_k-xexg" type="4001" element="_sBt-qgnVEe65vrT_k-xexg" source="_jxi4NAnVEe65vrT_k-xexg" target="_ucaffQnVEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sBt-sAnVEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sBt-sQnVEe65vrT_k-xexg" x="-59" y="1"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sBt-rgnVEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sBt-rwnVEe65vrT_k-xexg" points="[0, 22, -125, -98]$[0, 119, -125, -1]$[55, 119, -70, -1]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vpA20AoUEe67ybv37Ys8Ww" id="(0.45714285714285713,0.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1NgYwwnVEe65vrT_k-xexg" type="4001" element="_1NgYwAnVEe65vrT_k-xexg" source="_l5bxyQnVEe65vrT_k-xexg" target="_2Bv5LQnVEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1NgYxgnVEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1NgYxwnVEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1NgYxAnVEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1NgYxQnVEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3oAFTgnVEe65vrT_k-xexg" type="4001" element="_3oAFSwnVEe65vrT_k-xexg" source="_2Bv5LQnVEe65vrT_k-xexg" target="_FBnKvAnWEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3oAFUQnVEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3oAFUgnVEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3oAFTwnVEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3oAFUAnVEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VSNEUwnWEe65vrT_k-xexg" type="4001" element="_VSNEUAnWEe65vrT_k-xexg" source="_UPOkaAnWEe65vrT_k-xexg" target="_vbT7PAnWEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VSNEVgnWEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VSNEVwnWEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VSNEVAnWEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VSNEVQnWEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cK7PpwnWEe65vrT_k-xexg" type="4001" element="_cK7PpAnWEe65vrT_k-xexg" source="_vbT7PAnWEe65vrT_k-xexg" target="_d1abhAnWEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cK7PqgnWEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cK7PqwnWEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cK7PqAnWEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cK7PqQnWEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hL-uugnWEe65vrT_k-xexg" type="4001" element="_hL-utwnWEe65vrT_k-xexg" source="_d1abhAnWEe65vrT_k-xexg" target="_hg2yhAnWEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hL-uvQnWEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hL-uvgnWEe65vrT_k-xexg" x="-3" y="-27"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hL-uuwnWEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hL-uvAnWEe65vrT_k-xexg" points="[0, 22, 41, -402]$[0, 424, 41, 0]$[-19, 424, 22, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iobengnWEe65vrT_k-xexg" type="4001" element="_iobemwnWEe65vrT_k-xexg" source="_hg2yhAnWEe65vrT_k-xexg" target="_iobemAnWEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iobeoQnWEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iobeognWEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iobenwnWEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iobeoAnWEe65vrT_k-xexg" points="[0, 22, -1, -108]$[0, 90, -1, -40]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1nP5CwnWEe65vrT_k-xexg" type="4001" element="_1nP5CAnWEe65vrT_k-xexg" source="_d1abhAnWEe65vrT_k-xexg" target="_3eOozQnWEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1nP5DgnWEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1nP5DwnWEe65vrT_k-xexg" x="22" y="-27"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1nP5DAnWEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1nP5DQnWEe65vrT_k-xexg" points="[22, 0, -155, -409]$[166, 0, -11, -409]$[166, 384, -11, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7owvhQnWEe65vrT_k-xexg" type="4001" element="_7owvggnWEe65vrT_k-xexg" source="_3eOozQnWEe65vrT_k-xexg" target="_DEuKwwnXEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7owviAnWEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7owviQnWEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7owvhgnWEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7owvhwnWEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9aNfBgnWEe65vrT_k-xexg" type="4001" element="_9aNfAwnWEe65vrT_k-xexg" source="_DEuKwwnXEe65vrT_k-xexg" target="_-vOKLQnWEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9aNfCQnWEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9aNfCgnWEe65vrT_k-xexg" x="-20" y="28"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9aNfBwnWEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9aNfCAnWEe65vrT_k-xexg" points="[0, -21, -140, 236]$[0, -254, -140, 3]$[70, -254, -70, 3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_A91WwwnXEe65vrT_k-xexg" type="4001" element="_A91WwAnXEe65vrT_k-xexg" source="_-vOKLQnWEe65vrT_k-xexg" target="_DbzOBAnXEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_A91WxgnXEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_A91WxwnXEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_A91WxAnXEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_A91WxQnXEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FekXCgnXEe65vrT_k-xexg" type="4001" element="_FekXBwnXEe65vrT_k-xexg" source="_DbzOBAnXEe65vrT_k-xexg" target="_FekXAwnXEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Fek-EAnXEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Fek-EQnXEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FekXCwnXEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FekXDAnXEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IXV6-wnXEe65vrT_k-xexg" type="4001" element="_IXV6-AnXEe65vrT_k-xexg" source="_DbzOBAnXEe65vrT_k-xexg" target="_IXV69AnXEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IXV6_gnXEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IXV6_wnXEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IXV6_AnXEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IXV6_QnXEe65vrT_k-xexg" points="[0, 22, -199, -58]$[0, 79, -199, -1]$[184, 79, -15, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gFr_kAnXEe65vrT_k-xexg" type="4001" element="_gFpjUAnXEe65vrT_k-xexg" source="_DEuKwwnXEe65vrT_k-xexg" target="_IXV69AnXEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gFr_kwnXEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gFr_lAnXEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gFr_kQnXEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gFr_kgnXEe65vrT_k-xexg" points="[0, -8, -486, 177]$[486, -8, 0, 177]$[486, -171, 0, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gFsmoAnXEe65vrT_k-xexg" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mzWKYwnXEe65vrT_k-xexg" type="4001" element="_mzWKYAnXEe65vrT_k-xexg" source="_iobemAnWEe65vrT_k-xexg" target="_FekXAwnXEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mzWKZgnXEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mzWKZwnXEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mzWKZAnXEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mzWKZQnXEe65vrT_k-xexg" points="[0, 10, -948, 372]$[954, 10, 6, 372]$[954, -362, 6, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mzWxcAnXEe65vrT_k-xexg" id="(1.0,0.37037037037037035)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oSpZ8AnXEe65vrT_k-xexg" id="(0.3333333333333333,0.9666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tR6wUwnXEe65vrT_k-xexg" type="4001" element="_tR6wUAnXEe65vrT_k-xexg" source="_FBnKvAnWEe65vrT_k-xexg" target="_FekXAwnXEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tR6wVgnXEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tR6wVwnXEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tR6wVAnXEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tR6wVQnXEe65vrT_k-xexg" points="[0, 0, -1303, -592]$[1307, 0, 4, -592]$[1307, 577, 4, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tR7XYAnXEe65vrT_k-xexg" id="(1.0,0.5166666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vP-YcAnXEe65vrT_k-xexg" id="(0.26666666666666666,0.03333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NZoTownYEe65vrT_k-xexg" type="4001" element="_NZoToAnYEe65vrT_k-xexg" source="_eF0rgwnVEe65vrT_k-xexg" target="_OtB1PAnYEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NZoTpgnYEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NZoTpwnYEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NZoTpAnYEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NZoTpQnYEe65vrT_k-xexg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OSIB4wnYEe65vrT_k-xexg" type="4001" element="_OSIB4AnYEe65vrT_k-xexg" source="_OtB1PAnYEe65vrT_k-xexg" target="_jxi4NAnVEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OSIo8AnYEe65vrT_k-xexg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OSIo8QnYEe65vrT_k-xexg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OSIB5AnYEe65vrT_k-xexg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OSIB5QnYEe65vrT_k-xexg" points="[0, 2, -46, 5]$[41, 13, -5, 16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OSIo8gnYEe65vrT_k-xexg" id="(1.0,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hR1q0AnxEe6tX-7CHFY2xQ" type="4003" element="_hR0csAnxEe6tX-7CHFY2xQ" source="_hRyngAnxEe6tX-7CHFY2xQ" target="_FBnKvAnWEe65vrT_k-xexg">
      <styles xmi:type="notation:FontStyle" xmi:id="_hR1q0QnxEe6tX-7CHFY2xQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hR1q0gnxEe6tX-7CHFY2xQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_j87_IgnxEe6tX-7CHFY2xQ" type="4003" element="_j87_IQnxEe6tX-7CHFY2xQ" source="_j87YEQnxEe6tX-7CHFY2xQ" target="_vbT7PAnWEe65vrT_k-xexg">
      <styles xmi:type="notation:FontStyle" xmi:id="_j87_IwnxEe6tX-7CHFY2xQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_j87_JAnxEe6tX-7CHFY2xQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZQS8oAn5Ee6tX-7CHFY2xQ" type="4001" element="_ZQSVkAn5Ee6tX-7CHFY2xQ" source="_-RnTDAnUEe65vrT_k-xexg" target="_ZhLRRAn5Ee6tX-7CHFY2xQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZQS8own5Ee6tX-7CHFY2xQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZQS8pAn5Ee6tX-7CHFY2xQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZQS8oQn5Ee6tX-7CHFY2xQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZQS8ogn5Ee6tX-7CHFY2xQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZxoIEwn5Ee6tX-7CHFY2xQ" type="4001" element="_ZxoIEAn5Ee6tX-7CHFY2xQ" source="_ZhLRRAn5Ee6tX-7CHFY2xQ" target="_eF0rgwnVEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZxovIAn5Ee6tX-7CHFY2xQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZxovIQn5Ee6tX-7CHFY2xQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZxoIFAn5Ee6tX-7CHFY2xQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZxoIFQn5Ee6tX-7CHFY2xQ" points="[-2, -8, -528, 98]$[539, -8, 13, 98]$[539, -91, 13, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZxpWMAn5Ee6tX-7CHFY2xQ" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZxpWMQn5Ee6tX-7CHFY2xQ" id="(0.18604651162790697,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_afALcAn5Ee6tX-7CHFY2xQ" type="4001" element="_ae9IIAn5Ee6tX-7CHFY2xQ" source="_ZhLRRAn5Ee6tX-7CHFY2xQ" target="_A7AXJAnVEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_afALcwn5Ee6tX-7CHFY2xQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_afALdAn5Ee6tX-7CHFY2xQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_afALcQn5Ee6tX-7CHFY2xQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_afALcgn5Ee6tX-7CHFY2xQ" points="[-22, -29, 0, 81]$[-22, -88, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_afALdQn5Ee6tX-7CHFY2xQ" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yeJQ4AoUEe67ybv37Ys8Ww" type="4001" element="_yeIp0AoUEe67ybv37Ys8Ww" source="_ucaffQnVEe65vrT_k-xexg" target="_5E47aAoUEe67ybv37Ys8Ww" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yeJQ4woUEe67ybv37Ys8Ww" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yeJQ5AoUEe67ybv37Ys8Ww" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yeJQ4QoUEe67ybv37Ys8Ww" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yeJQ4goUEe67ybv37Ys8Ww" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_y6hq4AoUEe67ybv37Ys8Ww" type="4001" element="_y6hD0AoUEe67ybv37Ys8Ww" source="_5E47aAoUEe67ybv37Ys8Ww" target="_UPOkaAnWEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_y6hq4woUEe67ybv37Ys8Ww" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_y6hq5AoUEe67ybv37Ys8Ww" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_y6hq4QoUEe67ybv37Ys8Ww" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_y6hq4goUEe67ybv37Ys8Ww" points="[0, 0, -86, 60]$[87, -90, 1, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_y6iR8AoUEe67ybv37Ys8Ww" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_y6iR8QoUEe67ybv37Ys8Ww" id="(0.02,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_83x20AoXEe67ybv37Ys8Ww" type="4001" element="_83vakAoXEe67ybv37Ys8Ww" source="__esrMAoWEe67ybv37Ys8Ww" target="_hg2yhAnWEe65vrT_k-xexg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_83x20woXEe67ybv37Ys8Ww" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_83x21AoXEe67ybv37Ys8Ww" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_83x20QoXEe67ybv37Ys8Ww" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_83x20goXEe67ybv37Ys8Ww" points="[0, 0, -154, -459]$[155, 456, 1, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_83zE8AoXEe67ybv37Ys8Ww" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_83zE8QoXEe67ybv37Ys8Ww" id="(0.23255813953488372,0.27906976744186046)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
